import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ChildProps } from "@/types";
import { Toaster } from "@/components/ui/sonner";
import { LanguageProvider } from "@/contexts/language-context";
import "./globals.css";
import { BASE_URL } from "@/lib/constants";

const inter = Inter({
  weight: ["100", "300", "500", "700", "900"],
  subsets: ["latin", "cyrillic"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  metadataBase: new URL(BASE_URL),
  title: "Mahorat Soft",
  description: "Generated by create next app",
  authors: [{ name: "Mahorat Soft", url: BASE_URL }],
  icons: { icon: "/logo.png" },
  openGraph: {
    title: "Mahorat Soft",
    description:
      "Codeuz programming courses, internships, startup projects and most importantly quality education.",
    type: "website",
    url: BASE_URL,
    locale: "en_US",
    images: "https://i.postimg.cc/wxGP5Njc/codeuz-high-resolution-logo.png",
    countryName: "Uzbekistan",
    siteName: "Mahorat Soft",
    emails: "tulaganovok04@gmail.com",
  },
  keywords:
    "Praktikum, Praktikum Codeuz, NextJS, NextJS full course, NextJS course, NextJS programming, Startup, Startup project, Startup Codeuz, Codeuz, Codeuz practicum, Codeuz programming, Codeuz startup, Codeuz course, Codeuz courses, Codeuz programming courses, Codeuz startup courses, Codeuz startup projects, Codeuz startup project, Codeuz startup project, Codeuz startup project programming",
};

export default function RootLayout({ children }: Readonly<ChildProps>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <LanguageProvider>
          {children}
          <Toaster />
        </LanguageProvider>
      </body>
    </html>
  );
}
